In [1]:
import numpy as np

arr = np.array([0,1,2,3,4,5])
print(arr)

[0 1 2 3 4 5]


In [2]:
zeros = np.zeros(5)
ones = np.ones((2,3))
print(zeros)
print(ones)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
random_arr = np.random.rand(3,3)
print(random_arr)

[[0.64922523 0.12756179 0.55314614]
 [0.4868172  0.65779659 0.49642904]
 [0.40964835 0.54104841 0.15625439]]


In [4]:
arr = np.array([1,2,3,4,5,6])
print(arr)
reshape = arr.reshape((2,3))
print(reshape)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([1,2,3])
print(arr[0])
print(arr[1:4])

1
[2 3]


In [6]:
arr1 = np.array([21,21,21])
arr2 = np.array([10,10,10])
toplam = arr1+arr2
print(toplam)

[31 31 31]


In [7]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

3.0
3.0
1.4142135623730951


In [8]:
arr = np.array([1,2,3])
result = arr*2
print(result)

[2 4 6]


In [9]:
arr = np.array([10,20,30,40,50,60,70])
result = arr[arr>30]
print(result)

[40 50 60 70]


In [12]:
arr = np.array([1,2,3,4,5])
result = np.exp(arr)
print(result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

result = np.dot(A,B)
print(result)

det = np.linalg.det(A)
print(det)

[[19 22]
 [43 50]]
-2.0000000000000004


In [18]:
arr = np.array([1,31,31,234,234235])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.cumsum(arr))

234532
1
234235
[     1     32     63    297 234532]


In [20]:
arr = np.array([50,20,30,10,40])


sorted_arr = np.sort(arr)
print(sorted_arr)

indices = np.where(arr>30)
print(indices)

[10 20 30 40 50]
(array([0, 4]),)


In [30]:
arr1 = np.array([1.0,2.6,3])
arr2 = np.array([4,5,6])
concat = np.concatenate((arr1,arr2))
print(concat)
intarr = arr1.astype(int)
print(intarr)

str1 = "Levent"
str_arr = arr1.astype(str)
print(str_arr)
print(str_arr[0]+str_arr[1])
print(arr1[0]+arr1[1])

[1.  2.6 3.  4.  5.  6. ]
[1 2 3]
['1.0' '2.6' '3.0']
1.02.6
3.6


In [35]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [36]:
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [37]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
