In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
df=pd.read_csv('Student_Grades.csv')
df.head()

Hours  Practice  TeamWork  MidTerm  FinalExam  Scores Grade
0    2.5       0.5       0.0        2        2.3      21     C
1    5.1       1.5       0.5        4        4.9      47     B
2    3.2       1.0       0.5        3        2.9      27     C
3    8.5       3.7       1.2        7        7.7      75     A
4    3.5       1.2       0.3        3        3.2      30     C

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Hours      25 non-null     float64
 1   Practice   25 non-null     float64
 2   TeamWork   25 non-null     float64
 3   MidTerm    25 non-null     int64  
 4   FinalExam  25 non-null     float64
 5   Scores     25 non-null     int64  
 6   Grade      25 non-null     object 
dtypes: float64(4), int64(2), object(1)
memory usage: 1.5+ KB


In [4]:
df.columns

Index(['Hours', 'Practice', 'TeamWork', 'MidTerm', 'FinalExam', 'Scores',
       'Grade'],
      dtype='object')

In [5]:
df.isnull().sum()

Hours        0
Practice     0
TeamWork     0
MidTerm      0
FinalExam    0
Scores       0
Grade        0
dtype: int64

In [6]:
df.dtypes

Hours        float64
Practice     float64
TeamWork     float64
MidTerm        int64
FinalExam    float64
Scores         int64
Grade         object
dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [8]:
df['Grade'] = label_encoder.fit_transform(df['Grade'])
df.dtypes

Hours        float64
Practice     float64
TeamWork     float64
MidTerm        int64
FinalExam    float64
Scores         int64
Grade          int32
dtype: object

In [9]:
df.head()

Hours  Practice  TeamWork  MidTerm  FinalExam  Scores  Grade
0    2.5       0.5       0.0        2        2.3      21      2
1    5.1       1.5       0.5        4        4.9      47      1
2    3.2       1.0       0.5        3        2.9      27      2
3    8.5       3.7       1.2        7        7.7      75      0
4    3.5       1.2       0.3        3        3.2      30      2

In [10]:
x = df.drop(columns=["Scores","Grade"])
y = df["Scores"] 

In [11]:
x = x.values.astype('float32')
y = y.values.astype('float32')

In [12]:
x

array([[2.5, 0.5, 0. , 2. , 2.3],
       [5.1, 1.5, 0.5, 4. , 4.9],
       [3.2, 1. , 0.5, 3. , 2.9],
       [8.5, 3.7, 1.2, 7. , 7.7],
       [3.5, 1.2, 0.3, 3. , 3.2],
       [1.5, 0.2, 0. , 2. , 2.2],
       [9.2, 4.8, 3. , 8. , 9. ],
       [5.5, 3.2, 2. , 6. , 6.2],
       [8.3, 5.1, 3.5, 8. , 8.3],
       [2.7, 1.5, 0. , 3. , 2.7],
       [7.7, 4.9, 4.5, 8. , 8.7],
       [5.9, 3.1, 2.1, 6. , 6.4],
       [4.5, 2.8, 1. , 4. , 4.3],
       [3.3, 2.2, 1.1, 4. , 4.4],
       [1.1, 1.1, 0. , 2. , 1.9],
       [8.9, 6.2, 6. , 9. , 9.7],
       [2.5, 1.6, 1. , 3. , 3.2],
       [1.9, 0.9, 0.5, 2. , 2.6],
       [6.1, 2. , 3.2, 6. , 6.9],
       [7.4, 2.5, 3. , 7. , 7.1],
       [2.7, 3. , 1.2, 3. , 3.2],
       [4.8, 2.9, 2.1, 5. , 5.6],
       [3.8, 2.2, 0.3, 3. , 3.7],
       [6.9, 5.1, 3.8, 7. , 7.8],
       [7.8, 5.8, 4.5, 8. , 8.8]], dtype=float32)

In [13]:
y

array([21., 47., 27., 75., 30., 20., 88., 60., 81., 25., 85., 62., 41.,
       42., 17., 95., 30., 24., 67., 69., 30., 54., 35., 76., 86.],
      dtype=float32)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.70,random_state=42)

In [15]:
print(x_train.shape)
print(y_train.shape)

(17, 5)
(17,)


In [16]:
model = Sequential()

model.add(Dense(16))
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(1,activation="relu"))

model.compile(optimizer="adam",loss='mse',metrics=["mae"])
model.fit(x_train,y_train,epochs=512,batch_size=32)

Epoch 1/512
1/1 [==============================] - 0s 396ms/step - loss: 3454.0647 - mae: 52.7472
Epoch 2/512
1/1 [==============================] - 0s 4ms/step - loss: 3440.7922 - mae: 52.6398
Epoch 3/512
1/1 [==============================] - 0s 4ms/step - loss: 3425.7246 - mae: 52.5186
Epoch 4/512
1/1 [==============================] - 0s 4ms/step - loss: 3408.8943 - mae: 52.3834
Epoch 5/512
1/1 [==============================] - 0s 3ms/step - loss: 3389.9048 - mae: 52.2309
Epoch 6/512
1/1 [==============================] - 0s 5ms/step - loss: 3367.9753 - mae: 52.0553
Epoch 7/512
1/1 [==============================] - 0s 3ms/step - loss: 3344.3254 - mae: 51.8653
Epoch 8/512
1/1 [==============================] - 0s 4ms/step - loss: 3319.1375 - mae: 51.6626
Epoch 9/512
1/1 [==============================] - 0s 5ms/step - loss: 3292.1953 - mae: 51.4446
Epoch 10/512
1/1 [==============================] - 0s 3ms/step - loss: 3263.2463 - mae: 51.2082
Epoch 11/512
1/1 [===================

In [17]:
model.predict(np.expand_dims(x_test[0], axis=0))

1/1 [==============================] - 0s 94ms/step


array([[84.63958]], dtype=float32)

In [18]:
y_test[0]

81.0

In [19]:
model.predict(np.expand_dims(x_test[1], axis=0))

1/1 [==============================] - 0s 15ms/step


array([[29.766186]], dtype=float32)

In [20]:
y_test[1]

30.0