In [1]:
import numpy as np

In [2]:
iris = np.array([5.7,2.6,3.5,1.0])
print(iris)

[5.7 2.6 3.5 1. ]


In [3]:
iris2 = np.array([[2,5,7]])
print(iris2)

[[2 5 7]]


In [4]:
iris3 = np.array([[2,5,7],[3,6,8]])
print(iris3)

[[2 5 7]
 [3 6 8]]


In [5]:
print(np.zeros(3))

[0. 0. 0.]


In [6]:
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(np.zeros((2,4,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
print(np.ones(3))
print("-------")
print(np.ones((3,3)))

[1. 1. 1.]
-------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(np.full((2,2),"Levent"))

[['Levent' 'Levent']
 ['Levent' 'Levent']]


In [10]:
print(np.arange(0,2,0.2))

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [11]:
print(np.linspace(0.0,1.0,num=5))
print(np.linspace(0.0,1.0,num=5,endpoint=False))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]


In [12]:
print(np.random.rand(2,2))
print("--------------")
print(np.random.randint(3,7,size=(2,4)))

[[0.87979378 0.21869224]
 [0.49110184 0.36610213]]
--------------
[[3 6 4 5]
 [4 6 3 3]]


In [13]:
dizi = np.arange(2.0,9.0)
print(dizi.dtype,dizi)

float64 [2. 3. 4. 5. 6. 7. 8.]


In [14]:
dizi = np.arange(2.0,9.0,dtype="float64")
print(dizi.itemsize)
dizi2 = np.arange(2.0,9.0,dtype="float32")
print(dizi2.itemsize)
dizi3 = np.arange(2.0,9.0,dtype="int64")
print(dizi3.itemsize)

8
4
8


In [15]:
dizi = np.arange(16)
print(dizi.shape)
dizi.shape = (4,4)
print(dizi)
print('Boyut',dizi.ndim)

(16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Boyut 2


In [16]:
dizi = np.array([[2,5,7],[3,6,8]])
print(dizi)
dizi.ravel()

[[2 5 7]
 [3 6 8]]


array([2, 5, 7, 3, 6, 8])

In [17]:
dizi1 = np.array([4,6,8,9])
dizi2 = np.array([2,4,3,5])
print("Toplam:",dizi1+dizi2)
print("Fark:",dizi1-dizi2)
print("Carpma:",dizi1*dizi2)
print("Bolum:",dizi1/dizi2)
print("Bolum(tam):",dizi1//dizi2)
print("kalan:",dizi1%dizi2)
print("Ust:",dizi1**dizi2)

Toplam: [ 6 10 11 14]
Fark: [2 2 5 4]
Carpma: [ 8 24 24 45]
Bolum: [2.         1.5        2.66666667 1.8       ]
Bolum(tam): [2 1 2 1]
kalan: [0 2 2 4]
Ust: [   16  1296   512 59049]


In [18]:
print("Ust",2**31)

Ust 2147483648


In [27]:
dizi = np.array([[1,2.5,6],[8,20,11]])
for i in (dizi.min,dizi.max,dizi.sum,dizi.prod,dizi.std,dizi.var):
    print(i.__name__,"=",i())

min = 1.0
max = 20.0
sum = 48.5
prod = 26400.0
std = 6.274396828027022
var = 39.36805555555556


In [31]:
import pandas as pd
dizi = pd.DataFrame(dizi)
dizi.describe().T

count   mean        std  min    25%    50%     75%   max
0    2.0   4.50   4.949747  1.0  2.750   4.50   6.250   8.0
1    2.0  11.25  12.374369  2.5  6.875  11.25  15.625  20.0
2    2.0   8.50   3.535534  6.0  7.250   8.50   9.750  11.0

In [43]:
dizi = np.array([[1,2.5,6],[8,20,11]])
for i in (np.abs,np.sqrt,np.ceil,np.isnan):
    print("\n",i.__name__)
    print(i(dizi))
# Abs:absolute ifadesi kullanılabilir
# Fabs:abs den farkı mutlak değeri hesaplarken değer integer tipinde olsa da sonucu float döndürür
# Square: kare alma
# exp: dizinin üstel değerini hesaplar
# sign: dizi içindeki elemanların işaretini verir (+:1,-:0)


 absolute
[[ 1.   2.5  6. ]
 [ 8.  20.  11. ]]

 sqrt
[[1.         1.58113883 2.44948974]
 [2.82842712 4.47213595 3.31662479]]

 ceil
[[ 1.  3.  6.]
 [ 8. 20. 11.]]

 isnan
[[False False False]
 [False False False]]


In [45]:
dizi = np.array([5,12,4,-2,15,6,8,0])
print(dizi[4])
print(len(dizi))
print(dizi[1:5])
print(dizi[3:-1])
print(dizi[:4])
print(dizi[1::2])#ikişer atlayarak
dizi[2:4] = 11 #4 dahil
print(dizi)

15
8
[12  4 -2 15]
[-2 15  6  8]
[ 5 12  4 -2]
[12 -2  6  0]
[ 5 12 11 11 15  6  8  0]


In [46]:
yeniDizi = dizi[2:4]
print(yeniDizi)

[11 11]


In [62]:
dizi = np.arange(12)
dizi.shape = (3,4)
print(dizi)
print(dizi[2,3])
print(dizi[0,:])
print(dizi[:,2])
print("------------")
print(dizi[0:2,0:3])
dizi.shape=(3,2,2)
print(dizi)
print(dizi[1,1,0])
print(dizi[1,:,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
[0 1 2 3]
[ 2  6 10]
------------
[[0 1 2]
 [4 5 6]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
6
[4 6]


In [68]:
dizi1 = np.full((2,4),0.0)
dizi2 = np.full((2,4),1.0)
dizi3 = np.full((2,4),2.0)
print(dizi1)
print(dizi2)
print(dizi3)
dizi4 = np.concatenate((dizi1,dizi2,dizi3),axis=0)
print(dizi4)
dizi5 = np.concatenate((dizi1,dizi2,dizi3),axis=1)
print(dizi5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2.]
 [0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2.]]
